substitutions:
  device_name: "common"
  friendly_name: "Common"
  brand_name: "DiraSmart"
  primary_color: "#03A9F4"
  # logo_url: "https://raw.githubusercontent.com/jbrandek/esphome-packages/main/logo.png"

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"

# Use custom captive portal component
external_components:
  - source: github://jbrandek/esphome-packages/components
    components: [captive_portal]
    refresh: 1d

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} AP"
    password: "1234567890"

# Custom captive portal with logo, reboot and factory reset buttons
captive_portal:
  brand_name: "${brand_name}"
  primary_color: "${primary_color}"
  # logo_url: "${logo_url}"

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: status
    name: "${friendly_name} Connect"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "SSID"
    mac_address:
      name: "${friendly_name} MAC Address"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Strength"
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Reboot"
    entity_category: config

  - platform: factory_reset
    name: "${friendly_name} Factory Reset"
    entity_category: config

switch:
  - platform: safe_mode
    name: "${friendly_name} Safe Mode"
    id: device_safe_mode
    entity_category: config
