substitutions:
  device_name: "switch-2"
  friendly_name: "Switch 2"
  light_name_1: "Light 1"
  light_name_2: "Light 2"

esphome:
  name: ${device_name}
  on_boot:
    then:
      - light.control:
          id: my_light_1
          state: !lambda return id(last_light1_state);
      - light.control:
          id: green_led_1
          state: !lambda return id(last_light1_state);
      - light.control:
          id: my_light_2
          state: !lambda return id(last_light2_state);
      - light.control:
          id: green_led_2
          state: !lambda return id(last_light2_state);
  project:
    name: DiraSmart.Switch-2-NS
    version: "CB3S"

dashboard_import:
  package_import_url: github://jbrandek/esphome-packages-dev/gel-2-cb3s-ns.yaml@main
  import_full_config: false

bk72xx:
  board: cb3s

# Custom captive portal with DiraSmart branding
external_components:
  - source: github://jbrandek/esphome-packages-dev/components
    components: [captive_portal]
    refresh: 1d

#packages:
  #common: github://jbrandek/esphome-packages/common.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
  #on_error:
  #- button.press: restart_button

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} AP"
    password: "1234567890"

mdns:
  disabled: false

captive_portal:
  brand_name: "DiraSmart"
  primary_color: "#03A9F4"

time:
  - platform: homeassistant
    id: homeassistant_time

globals:
  - id: last_light1_state
    type: boolean
    restore_value: yes
    initial_value: 'false'
  - id: last_light2_state
    type: boolean
    restore_value: yes
    initial_value: 'false'

preferences:
  flash_write_interval: 30s #(time in seconds e.g. 30s)

output:
  - platform: gpio
    pin: 
      number: P6
    id: switch_output_1

  - platform: gpio
    pin:
      number: P11
      # P21 WB3S
    inverted: true      
    id: green_led_output_1
  
  - platform: gpio
    pin: 
      number: P8
    id: switch_output_2

  - platform: gpio
    pin:
      number: P14
    inverted: true      
    id: green_led_output_2
    
  - platform: gpio
    pin:
      number: P20
      # P11 WB3S
    inverted: true
    id: wifi_led_output


light:
  - platform: binary
    name: WiFi LED
    restore_mode: RESTORE_DEFAULT_ON
    id: wifi_led
    disabled_by_default: true
    output: wifi_led_output
    
  - platform: binary
    restore_mode: RESTORE_DEFAULT_OFF
    name: ${light_name_1}
    id: my_light_1
    output: switch_output_1
    on_turn_on:
      - light.turn_on: green_led_1
      - globals.set:
          id: last_light1_state
          value: 'true'
    on_turn_off:
      - light.turn_off: green_led_1
      - globals.set:
          id: last_light1_state
          value: 'false'

  - platform: binary
    restore_mode: RESTORE_DEFAULT_OFF
    id: green_led_1
    output: green_led_output_1
  
  - platform: binary
    restore_mode: RESTORE_DEFAULT_OFF
    name: ${light_name_2}
    id: my_light_2
    output: switch_output_2
    on_turn_on:
      - light.turn_on: green_led_2
      - globals.set:
          id: last_light2_state
          value: 'true'
    on_turn_off:
      - light.turn_off: green_led_2
      - globals.set:
          id: last_light2_state
          value: 'false'

  - platform: binary
    restore_mode: RESTORE_DEFAULT_OFF
    id: green_led_2
    output: green_led_output_2
  
  - platform: status_led
    id: blue_led
    pin:
      number: P23
      inverted: true

binary_sensor:
  - platform: status
    name: "Connect"
  - platform: gpio
    internal: true
    pin:
      number: P24
      inverted: true
      mode: INPUT_PULLUP
    name: ${device_name}_button_1 
    id: relay_button_1
    on_multi_click:
      - timing:
          - ON for 40ms to 800ms
          - OFF for at least 400ms
        then:
          - light.toggle: my_light_1
      - timing:
          # 5 click restart
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for at least 400ms
        then:
          - button.press:
              id: restart_button       
  
  - platform: gpio
    internal: true
    pin:
      number: P10
      mode: INPUT_PULLUP
      inverted: true
    name: ${device_name}_button_2
    id: relay_button_2
    on_multi_click:
      - timing:
          - ON for 40ms to 800ms
          - OFF for at least 400ms
        then:
          - light.toggle: my_light_2
      - timing:
          # 5 click restart
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for at least 400ms
        then:
          - button.press:
              id: restart_button

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "SSID"
    mac_address:
      name: "MAC Address"

sensor:
  - platform: wifi_signal
    name: "WiFi Strength"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"

button:
  - platform: restart
    id: restart_button
    name: "Reboot"
    entity_category: config

switch:
  - platform: safe_mode
    name: "Safe Mode"
    id: device_safe_mode
    entity_category: config

    
